version: "3.9"
   
services:
  db:
    container_name: mysql-db
    image: mysql:8.0
    restart: always
    volumes:
      - db_data_volume:/var/lib/mysql
    env_file:
      - ./backend/.env

  app:
    build: 
      dockerfile: ./docker/Dockerfile
    command: bash -c "sleep 5 && gunicorn --bind 0.0.0.0:8000 --workers=2 config.wsgi:application"
    volumes:
      - static_volume:/app/static
    env_file:
      - ./backend/.env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - static_volume:/app/static
    depends_on:
      - app

volumes:
  static_volume:
  db_data_volume: