# Generated by Django 4.0.6 on 2022-07-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='tenants',
        ),
    ]
